### ISSUE TITLE
id 입력시 도메인이 자동완성되는 기능 수정 필요

### ISSUE THREAD

**Issue by cnkqavsj** [cnkqavsj/conversations#2]
Register new account 페이지로 들어가서 id를 입력할 때

username@conversation.im 뒷부분 주소가 자동완성되는 기능

이것이 otherhome.au 로되면 좋고, 안되면 그냥 다 입력하는 형태
1번째화면
![image](https://user-images.githubusercontent.com/24556277/181207561-76d1d38c-17bc-48e9-996b-74b896f69683.png)

2번째화면
![image](https://user-images.githubusercontent.com/24556277/181220726-954f3d9d-b2eb-405a-98cc-11e5751701a0.png)

**Comment by begent** [comment]
test 완료
