### ISSUE TITLE
빌드시 에러

### ISSUE THREAD

**Issue by begent** [cnkqavsj/conversations#9]
브랜치: feature_color_textview_basedon_feature_img_

이후 다시 빌드하면 정상 출력됨
![image](https://user-images.githubusercontent.com/24556277/182021935-7f1552f6-7aac-456e-bf75-cf79de1c1af5.png)

**Comment by begent** [comment]
근데 실제 플레이스토어에 제출하는 파일은 apk 파일이라서 결론적으로 빌드만 되면 되는거 아닐까!?

**Comment by h-dog** [comment]
일단 나는 빌드 에러 안남...
feature_color_textview_basedon_feature_img_
